<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NutriPlan.Domain\NutriPlan.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="NovaPasta\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2025.12.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
